version: '3'
services:
  web:
    image: jonodrew/talent-tracker:latest
    volumes:
      - ./app:/code/app
      - ./migrations:/code/migrations
      - ./reporting:/code/reporting
      - ./modules:/code/modules
    depends_on:
      - db
    links:
      - db
    environment:
      - POSTGRES_USER=talent_user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=talent-tracker
      - POSTGRES_HOST=postgres
      - FLASK_DEBUG=1
      - DATABASE_URL=postgresql://talent_user:password@db:5432/talent-tracker
      - FLASK_APP=run.py
      - SECRET_KEY=secret-dev-key
    ports:
      - "5000:5000"

  python-tests:
    image: jonodrew/talent-tracker:latest
    volumes:
      - ./tests:/code/tests
    entrypoint: python -m pytest tests/
    depends_on:
      - db

  db:
    image: postgres:9.6
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=talent_user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=talent-tracker

    volumes:
      - talent-data:/var/lib/postgresql/data

volumes:
  talent-data:

