"""Add date to RoleChangeEvent

Revision ID: 4143633173ba
Revises: 6dad71d5a7d3
Create Date: 2020-04-05 07:42:37.196287

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "4143633173ba"
down_revision = "6dad71d5a7d3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "role_change_event", sa.Column("role_change_date", sa.Date(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("role_change_event", "role_change_date")
    # ### end Alembic commands ###
