"""Add secondary email address to Candidate model

Revision ID: 560e763c603d
Revises: 8bd57cbf8d7a
Create Date: 2019-09-26 14:40:33.722440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "560e763c603d"
down_revision = "8bd57cbf8d7a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "candidate",
        sa.Column("secondary_email_address", sa.String(length=120), nullable=True),
    )
    op.create_unique_constraint(None, "candidate", ["secondary_email_address"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "candidate", type_="unique")
    op.drop_column("candidate", "secondary_email_address")
    # ### end Alembic commands ###
