"""Remove date_started and promotion_id from Role

Revision ID: 5c1af380b29f
Revises: 4143633173ba
Create Date: 2020-04-05 17:49:58.738452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "5c1af380b29f"
down_revision = "4143633173ba"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("role_promotion_id_fkey", "role", type_="foreignkey")
    op.drop_column("role", "role_change_id")
    op.drop_column("role", "date_started")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "role", sa.Column("date_started", sa.DATE(), autoincrement=False, nullable=True)
    )
    op.add_column(
        "role",
        sa.Column("role_change_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.create_foreign_key(
        "role_promotion_id_fkey", "role", "promotion", ["role_change_id"], ["id"]
    )
    # ### end Alembic commands ###
