"""Add RoleChangeEvent table

Revision ID: 6dad71d5a7d3
Revises: 560e763c603d
Create Date: 2020-04-04 20:31:12.135039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "6dad71d5a7d3"
down_revision = "560e763c603d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "role_change_event",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("candidate_id", sa.Integer(), nullable=True),
        sa.Column("former_role_id", sa.Integer(), nullable=True),
        sa.Column("new_role_id", sa.Integer(), nullable=True),
        sa.Column("role_change_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["candidate_id"], ["candidate.id"],),
        sa.ForeignKeyConstraint(["former_role_id"], ["role.id"],),
        sa.ForeignKeyConstraint(["new_role_id"], ["role.id"],),
        sa.ForeignKeyConstraint(["role_change_id"], ["promotion.id"],),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("role_change_event")
    # ### end Alembic commands ###
